Ema/feat 142
tomasg88/bvlc pull request #145
Opened 2024-03-05 23:05 UTC by emagarc

In this feature, pagination is added to the news page of the website. Several packages related to styling management in Tailwind CSS, as well as a new SVG icon library called lucide-react, are installed. A file named utils.ts is added to the lib folder at the root of the project to handle some styling functions. Additionally, a new button named ButtonPagination is introduced, containing the button component along with some style configurations and variables. Subsequently, another component called Pagination is included, where the components for constructing pagination on the news page are defined. Finally, logic is implemented in the news section to manage the news list and only display 5 items.

2024-03-06 14:19 UTC, tomasg88 requested changes
En general lo veo bien, pero hay varias cosas por ajustar, revisá los comentarios. 
1. Me parece que no estás trabajando sobre los últimos cambios (`SanityClientOrProjectDetails`).
2. La dependencia de `lucide-react`, fijate si podes usar otros iconos del paquete que ya tenemos.
3. No funciona en modo responsive, sabés habilitarlo para revisar? Si no avisame y lo vemos juntos. Este punto igual podemos dejarlo para después.

2024-03-07 20:08 UTC, emagarc commented on components/ArticleContent/ArticleContent.tsx
> +            />
Hola Tom, si la verdad que si, y cuando fui realizando los commits en ningun momento los vi en el arbol de cambios lo cual me parece raro porque si, ya lo habia trabajado y terminado a ese cambio tambien había sido mergeado.

2024-03-07 20:09 UTC, emagarc commented on components/CardSpecialty/CardSpecialty.tsx
> +  const { src, loader } = useNextSanityImage(sanityConfig as SanityClientOrProjectDetails, cover);
Lo mismo que el anterior. No se cual es la causa de esto. De ultima da problemas al mergear?

2024-03-07 20:54 UTC, emagarc commented on components/Pagination/Pagination.tsx
> +import { ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react';
Hecho y desinstalado lucide-react.

2024-03-07 20:54 UTC, emagarc commented on components/Button/ButtonPagination.tsx
> +const Button = React.memo(
Hecho.

2024-03-07 20:54 UTC, emagarc commented on components/Pagination/Pagination.tsx
> +    aria-label="Go to next page"
Hecho.

2024-03-07 20:54 UTC, emagarc commented on components/Pagination/Pagination.tsx
> +    aria-label="Go to previous page"
Hecho.

2024-03-07 20:54 UTC, emagarc commented on lib/utils.ts
> +}
Hecho.

2024-03-20 22:21 UTC, tomasg88 reviewed
Varios comentarios, algunos no quiero darte la respuesta sino que puedas buscarlo y entender qué estaría bueno que mires.

2024-03-20 22:21 UTC, tomasg88 commented on components/Pagination/PaginationEllipsis.tsx
> +PaginationEllipsis.displayName = 'PaginationEllipsis';
Con este código hay un problema, llegas a verlo?

2024-03-20 22:21 UTC, tomasg88 commented on components/Pagination/ButtonPagination.tsx
> +);
Cómo se están usando todas estas clases? Se están usando todas estas clases?

2024-03-20 22:21 UTC, tomasg88 commented on utils/utils.ts
> +}
Con esto hay un problema también. Para qué se está usando esto?

2024-03-20 22:21 UTC, tomasg88 commented on pages/noticias.tsx
> +          <div className="max-w-5xl grid-cols-1 gap-6 px-6 pt-12 pb-10 mx-auto md:px-0 border-b-2 border-yellow-400">
Bien el bordecito 👍  💅

2024-03-20 22:21 UTC, tomasg88 commented on pages/noticias.tsx
> +  const [currentPage, setCurrentPage] = useState(1);
Esta línea está hecha en JavaScript. Cómo sería en Typescript?

2024-03-20 22:21 UTC, tomasg88 commented on components/Pagination/ButtonPagination.tsx
> +export { Button, buttonVariants };
Están bien los exports, pero estaría bueno unificar su formato.. O hacemos: 
* export en cada línea donde declaras una constante (`export const ...`)
* hacemos un export de un objeto al final (export { const, const2, ...}) 
* hacemos un export default (`export default bla...`).

O sea, anda bien igual, pero si podés mantener el mismo formato en un archivo es más legible.

2024-03-20 22:21 UTC, tomasg88 commented on components/Pagination/PaginationLink.tsx
> +export default PaginationLink;
Acá hay un parámetro que no estás usando, lo borrás?

2024-04-11 23:19 UTC, merged